// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBV8HnGH_JDA_TMjDonDdaFOAZzNIBpw3Q',
    appId: '1:24459761534:web:4ad2148e60a10b9935c52f',
    messagingSenderId: '24459761534',
    projectId: 'bmitest-a1c99',
    authDomain: 'bmitest-a1c99.firebaseapp.com',
    storageBucket: 'bmitest-a1c99.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWy5q115sikBauId0m_8Anhb2X4XGsmCg',
    appId: '1:24459761534:android:110e19d89297002335c52f',
    messagingSenderId: '24459761534',
    projectId: 'bmitest-a1c99',
    storageBucket: 'bmitest-a1c99.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3hvjexHYqF8b-5Lrvjo1O_hUJCq7I9g8',
    appId: '1:24459761534:ios:48b8b246b4cf1dd335c52f',
    messagingSenderId: '24459761534',
    projectId: 'bmitest-a1c99',
    storageBucket: 'bmitest-a1c99.firebasestorage.app',
    iosBundleId: 'com.example.mamatProject',
  );
}
